const SUPABASE_URL="https://ubkvpmwpvmozbhwlxhmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="PASTE_YOUR_SUPABASE_PUBLISHABLE_KEY_HERE";
const BACKEND_URL="PASTE_YOUR_NODE_BACKEND_URL_HERE";
const users=[{id:"rahul",name:"Rahul",gender:"boy",online:true,friends:true,unread:2,last:"Hey! How are you?"},{id:"priya",name:"Priya",gender:"girl",online:true,friends:true,unread:0,last:"See you later 👋"},{id:"aman",name:"Aman",gender:"boy",online:false,friends:false,unread:1,last:"That project looks cool."},{id:"neha",name:"Neha",gender:"girl",online:true,friends:true,unread:0,last:"Thanks!"}];
const state={filter:"online",selected:null,blocked:JSON.parse(localStorage.q1blocked||"[]"),messages:JSON.parse(localStorage.q1messages||"{}"),settings:JSON.parse(localStorage.q1settings||'{"name":"You","gender":"boy","age":"13-17"}')};
const $=x=>document.querySelector(x);const u=id=>users.find(x=>x.id===id);const save=()=>{localStorage.q1blocked=JSON.stringify(state.blocked);localStorage.q1messages=JSON.stringify(state.messages);localStorage.q1settings=JSON.stringify(state.settings)}
function renderUsers(){let q=$("#search").value.toLowerCase();let arr=users.filter(x=>!state.blocked.includes(x.id)&&x.name.toLowerCase().includes(q)).filter(x=>state.filter==="online"?x.online:state.filter==="unread"?x.unread:state.filter==="friends"?x.friends:true);$("#users").innerHTML=arr.map(x=>`<button class="user ${state.selected===x.id?"selected":""}" onclick="selectUser('${x.id}')"><span class="avatar ${x.gender}">${x.name[0]}</span><span class="info"><b>${x.name}<i class="dot ${x.online?'on':''}"></i></b><span class="preview">${x.last||''}</span></span>${x.unread?`<small>${x.unread}</small>`:''}</button>`).join("")||'<p style="padding:15px;color:#777">No users found.</p>'}
function selectUser(id){state.selected=id;u(id).unread=0;if(!state.messages[id])state.messages[id]=[{me:false,text:`Hi! I'm ${u(id).name}. 👋`}];save();$("#chatName").textContent=u(id).name;$("#status").innerHTML=`<span class="dot ${u(id).online?'on':''}"></span>${u(id).online?'Online':'Offline'}`;$("#input").disabled=false;$("#send").disabled=false;renderUsers();renderMessages()}
function renderMessages(){let box=$("#messages");if(!state.selected){box.innerHTML='<div class="welcome">💬<h2>Welcome to Q1 Chat</h2><p>Select a person to start a conversation.</p></div>';return}box.innerHTML=state.messages[state.selected].map(m=>`<div class="msg ${m.me?'me':''}">${escapeHtml(m.text)}<div class="meta">${m.time||''}</div></div>`).join('');box.scrollTop=box.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function blockedText(t){return /https?:\/\/\S+|www\.\S+|\b(instagram|snapchat|onlyfans|telegram|discord)\b|\b(dm me|link in bio|follow me|add me)\b/i.test(t)}
$("#send").onclick=()=>{let t=$("#input").value.trim();if(!t||!state.selected)return;if(blockedText(t)){alert('This message was blocked by Q1 Chat safety filters.');return}state.messages[state.selected].push({me:true,text:t,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});$("#input").value='';save();renderMessages()};$("#input").onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$("#send").click()}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderUsers()});$("#search").oninput=renderUsers;
$("#settingsBtn").onclick=()=>{$("#displayName").value=state.settings.name;$("#gender").value=state.settings.gender;$("#age").value=state.settings.age;settings.showModal()};$("#save").onclick=()=>{state.settings={name:$("#displayName").value.trim()||'You',gender:$("#gender").value,age:$("#age").value};save();settings.close()};$("#blocked").onclick=()=>{let list=$("#blockedList");list.innerHTML=state.blocked.map(id=>{let x=u(id);return x?`<div class="blockedrow"><span>${x.name}</span><button onclick="unblock('${id}')">Unblock</button></div>`:''}).join('')||'<p>No blocked users.</p>';blockedDialog.showModal()};function unblock(id){state.blocked=state.blocked.filter(x=>x!==id);save();blocked.click()}

$("#block").onclick=()=>{if(!state.selected)return;let id=state.selected;if(confirm(`Block ${u(id).name}?`)){state.blocked.push(id);state.selected=null;$("#input").disabled=true;$("#send").disabled=true;renderUsers();renderMessages();save()}};$("#report").onclick=()=>{if(state.selected)alert('Report submitted for moderation.')};renderUsers();
